name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Carthage
      run: carthage update --platform iOS
    - name: show simulator list
      run: xcrun instruments -s
    - name: xcode test
      run: xcodebuild test -project SwiftAppCenterSample.xcodeproj -scheme Debug -destination 'platform=iOS Simulator,name=iPhone Xs,OS=12.2'
      
